services:
  weaviate:
    image: semitechnologies/weaviate:1.24.0
    ports:
      - "9090:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: "none"
    volumes:
      - weaviate_data:/var/lib/weaviate
volumes:
  weaviate_data:
